[package]
name = "sovrin-client"
version = "0.1.0"
authors = [
  "Sergej Pupykin <sergej.pupykin@dsr-company.com>",
  "Vyacheslav Gudkov <vyacheslav.gudkov@dsr-company.com>",
  "Artem Ivanov <artem.ivanov@dsr-company.com>",
  "Evgeniy Razinkov <evgeniy.razinkov@dsr-company.com.ru>",
  "Kirill Neznamov <kirill.neznamov@dsr-company.com>",
  "Sergey Minaev <sergey.minaev@dsr-company.com>"
  ]

description = "Sovrin client with c-callable interface"
license = "MIT/Apache-2.0"
build = "build.rs"

[lib]
name = "sovrin"
path = "src/lib.rs"
crate-type = ["staticlib","rlib", "dylib"]

[[bin]]
name = "sovrin"
path = "src/main.rs"

[features]
default = ["bn_openssl", "ed25519_sodium", "base58_rust_base58", "xsalsa20_sodium", "pair_milagro", "hash_openssl", "local_nodes_pool"]
bn_openssl = ["openssl", "int_traits"]
ed25519_sodium = ["sodiumoxide"]
base58_rust_base58 = ["rust-base58"]
xsalsa20_sodium = ["sodiumoxide"]
pair_milagro = ["milagro-crypto"]
hash_openssl = ["openssl"]
local_nodes_pool = []

[dependencies]
int_traits = { version = "0.1.1", optional = true }
env_logger = "0.4.2"
libc = "0.2.21"
log = "0.3.7"
openssl = { version = "0.9.11", optional = true }
milagro-crypto = { version = "0.1.7", optional = true }
rand = "0.3"
rusqlite = "0.10.1"
rust-base58 = {version = "0.0.4", optional = true}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sodiumoxide = {version = "0.0.14", optional = true}
time = "0.1.36"
zmq = "0.8.1"
lazy_static = "0.2"
byteorder = "1.0.0"
[dependencies.uuid]
version = "0.5.0"
default-features = false
features = ["v4"]
